easy_admin:
    site_name: 'Draco Kowala'
    formats:
        date:     'd/m/Y'

    design:
        #templates: 
         #   paginator: 
        color_scheme: 'dark'
        brand_color: '#E82E2B'
        assets:
            css:
                #- '/bundles/clubblog/style.css'
            favicon: '/bundles/clubblog/images/draco.png'