#api_login_check:
#    path: /api/login_check
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
club_game:
    resource: "@ClubGameBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
club_user:
    resource: "@ClubUserBundle/Resources/config/routing.yml"
    prefix:   /
club_blog:
    resource: "@ClubBlogBundle/Resources/config/routing.yml"
    prefix:   /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"