easy_admin:
    entities:
        Season:
            class: Club\GameBundle\Entity\Season
            label: 'Sezon'
            edit:
                title: "Edytuj sezon"
            list:
                actions: 
                    - { name: 'new', label: 'Dodaj sezon',icon: 'plus'}
                    - { name: 'show', label: '', icon: 'eye' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                title: "Lista rozgrywek"
                fields: 
                    - { property: 'name', label: 'Nazwa' }
                    - { property: 'date', label: 'Data', type: 'date' }
                    - { property: 'team', label: 'Liczba drużyn' }
            show:
                title: 'Szczegóły sezonu'
                fields: 
                    - { property: 'name', label: 'Nazwa' }
                    - { property: 'date', label: 'Data', type: 'date' }
                    - { property: 'team', label: 'Lista drużyn' }
                    - { property: 'matches', label: 'Lista meczy' }
                    - { property: 'teamsNum', label: 'Liczba drużyn' }
            form:
                title: "Dodaj sezon"
                fields: 
                    - { property: 'name', label: 'Nazwa' }
                    - { property: 'date', label: 'Data', type: 'date' }
                    - { property: 'teamsNum', label: 'Liczba drużyn' }
                    - { property: 'team', label: 'Drużyny' }
#                    - { property: 'matches', label: 'Liczba stat. drużyn' }


 