Club\GameBundle\Entity\Position:
    relations:
        -
            rel: self
            href: 
                route: api_game_position_show
                parameters: 
                    slug: expr(object.getSlug())
                absolute: false  
        -
            rel: players
            href: 
                route: api_game_positions_players_list
                parameters: 
                    slug: expr(object.getSlug())
                absolute: false  
#        -
#            rel: position
#            embedded:
#                content: expr(object.getPosition())
#                max_depth: 0
#                exclusion:
#                    max_depth: 0
#                    groups: [list]
#            exclusion:
#                groups: [list]
#                max_depth: 0
#        -
#            rel: team
#            embedded:
#                content: expr(object.getTeam())
#                max_depth: 1
#            exclusion:
#                groups: [list]
#                max_depth: 1

    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order: [id, name, positionOrder]
    properties : 
        id:
            expose: true
        name:
            expose: true
        positionOrder:
            expose: true   
#        player:
#            serialized_name: players
#            expose: true           
#            max_depth: 1
#    virtual_properties:
#        getPositionName:
#            serialized_name: position
#            type: string
#        getPositionId:
#            serialized_name: positionId
#            type: integer
#        getTeamName:
#            serialized_name: team
#            type: string
#        getTeamId:
#            serialized_name: teamId
#            type: integer
    