Club\GameBundle\Entity\Season:
    relations:
        -
            rel: self
            href: 
                route: api_game_season_show
                parameters: 
                    id: expr(object.getId())
                absolute: false      
#        -
#            rel: team
#            href: 
#                route: api_game_team_show
#                parameters: 
#                    slug: expr(object.getTeam().getSlug())
#                absolute: false                   
#        -
#            rel: position
#            embedded:
#                content: expr(object.getPosition())
#                max_depth: 0
#                exclusion:
#                    max_depth: 0
#                    groups: [list]
#            exclusion:
#                groups: [list]
#                max_depth: 0
#        -
#            rel: team
#            embedded:
#                content: expr(object.getTeam())
#                max_depth: 1
#            exclusion:
#                groups: [list]
#                max_depth: 1

    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order: [id]
    properties: 
        id:
            expose: true
        name:
            expose: true   
        date:
            expose: true   
            type: DateTime<'Y-m-d'>
        teamsNum:
            expose: true
            serialized_name: teams_num
#    virtual_properties:
#        getPlayerName:
#            serialized_name: player_name
#            type: string
#        getPlayerId:
#            serialized_name: player_id
#            type: integer
#        getMatchName:
#            serialized_name: match
#            type: string
#        getMatchId:
#            serialized_name: match_id
#            type: integer