Club\GameBundle\Entity\PlayerStats:
    relations:
        -
            rel: self
            href: 
                route: api_game_player_stats_show
                parameters: 
                    id: expr(object.getId())
                absolute: false
        -
            rel: season
            href: 
                route: api_game_season_show
                parameters: 
                    id: expr(object.getSeason().getId())
                absolute: false               
        -
            rel: player
            href: 
                route: api_game_player_show
                parameters: 
                    slug: expr(object.getPlayer().getSlug())
                absolute: false  
#        -
#            rel: position
#            embedded:
#                content: expr(object.getPosition())
#                max_depth: 0
#                exclusion:
#                    max_depth: 0
#                    groups: [list]
#            exclusion:
#                groups: [list]
#                max_depth: 0
#        -
#            rel: team
#            embedded:
#                content: expr(object.getTeam())
#                max_depth: 1
#            exclusion:
#                groups: [list]
#                max_depth: 1

    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order: [id]
    properties: 
        id:
            expose: true
        matches:
            expose: true   
            type: integer
        goals:
            expose: true
        assists:
            expose: true
        redCards:
            expose: true
            serialized_name: red_cards   
        yellowCards:
            expose: true
            serialized_name: yellow_cards                                                                                                            
    virtual_properties:
        getPlayerName:
            serialized_name: player_name
            type: string
        getPlayerId:
            serialized_name: player_id
            type: integer
        getSeasonName:
            serialized_name: season
            type: string
        getSeasonId:
            serialized_name: season_id
            type: integer