<?php

namespace Club\GameBundle\Repository;

/**
 * ScoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistsRepository extends \Doctrine\ORM\EntityRepository
{
    public function createQueryBuilderForMatch($id)
    {
        return $this->createQueryBuilder('assists')
            ->leftJoin('assists.matches', 'matches')
            ->andWhere('matches.id = :id')
            ->setParameter('id', $id)
            ->getQuery()->getArrayResult();
    }
}
