<?php

namespace Club\GameBundle\Repository;

/**
 * PlayerStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayerStatistics($orderBy = null, $orderDir = null)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'player')
            ->leftJoin('p.player', 'player')
            ->leftJoin('player.position', 'position');

        if (!empty($orderBy)) {
            $qb->orderBy($orderBy, $orderDir);
        } else {
            $qb->orderBy('position.positionOrder', 'ASC');
        };

        return $qb->getQuery()->getResult();
    }
}
