<?php

namespace Club\GameBundle\Repository;

use Club\GameBundle\Entity\Position;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCadre($team)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p as player', 'position.name as positionName', 's')
            ->leftJoin('p.team', 't')
            ->leftJoin('p.position', 'position')
            ->leftJoin('p.playerStats', 's')
            ->orderBy('position.positionOrder')
            ->where('t.slug =:teamSlug')
            ->setParameter('teamSlug', $team);

        $query = $qb->getQuery()->getArrayResult();
        return $query;
    }

    public function createQueryBuilderForPosition($slug)
    {
        return $this->createQueryBuilder('player')
            ->leftJoin('player.position', 'position')
            ->andWhere('position.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()->getArrayResult();
    }

    public function createQueryBuilderForTeam($slug)
    {
        return $this->createQueryBuilder('player')
            ->select('player')
            ->leftJoin('player.team', 'team')
            ->andWhere('team.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()->getArrayResult();

    }
}
