<?php

namespace Club\GameBundle\Repository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayerStatisticsByPosition()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'player', 'playerStats')
            ->leftJoin('p.player', 'player')
            ->leftJoin('player.playerStats', 'playerStats')
            ->orderBy('p.positionOrder', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
