<?php

namespace Club\GameBundle\Repository;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllRounds($teams)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r as rounds', 'season.name AS seasonName', 'matches', 'r.name AS roundName')
            ->leftJoin('r.matches', 'matches')
            ->leftJoin('matches.season', 'season')
            ->orderBy('r.id')
            ->where('matches != :null')
            ->setParameter('null', 'NULL');
        return $qb->getQuery()->getResult();
    }
}
