<?php

namespace Club\GameBundle\Repository;

/**
 * ScoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoresRepository extends \Doctrine\ORM\EntityRepository
{
}
