<?php

namespace Club\GameBundle\Repository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastSeasonTeamsNumber()
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.teamsNum')
            ->orderBy('s.date', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
