<?php

namespace Club\GameBundle\Repository;

/**
 * TeamStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamStatsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTable()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.matches', 't.points', 'team.name')
            ->leftJoin('t.team', 'team')
            ->orderBy('t.points', 'DESC')
            ->addOrderBy('t.bilans', 'DESC');
        return $qb->getQuery()->getArrayResult();
    }

    public function getAllTable($orderBy = null, $orderDir = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.matches', 't.points', 'team.name', 't.bilans', 't.draws',
                't.goalsLost', 't.goalsScored', 't.loses', 'season.name AS seasonName', 't.wins')
            ->leftJoin('t.team', 'team')
            ->leftJoin('t.season', 'season');

        if (!empty($orderBy)) {
            $qb->orderBy($orderBy, $orderDir);
        } else {
            $qb->orderBy('t.points', 'DESC')
                ->addOrderBy('t.bilans', 'DESC');
        };

        return $qb->getQuery()->getResult();
    }

}
