easy_admin:
    entities:
        Post: 
            class: Club\BlogBundle\Entity\Post
            label: 'Posty'
            edit:
                title: "Edytuj post"
            list:
                actions: 
                    - { name: 'new', label: 'Dodaj Post', icon: 'plus' }
                    #- { name: 'show', label: '', icon: 'eye' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                title: "Lista Postów"
                fields:
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'thumbnail', label: 'Obraz', type: 'image' }
                    - { property: 'category.name', label: 'Kategoria' }
                    - { property: 'isMatch', label: 'Mecz' }
                    - { property: 'author', label: 'Autor' }
                    - { property: 'createDate', label: 'Data utworzenia' }
                    - { property: 'comments', label: 'Komentarzy:' }
                    - { property: 'isCommentable', label: 'Komentarze' }
                    - { property: 'match', label: 'Mecz' }
            form:
                title: "Dodaj post"
                fields:
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'thumbnailFile', label: 'Obraz', type: 'file'}
                    - { property: 'category', label: 'Kategoria' }
                    - { property: 'isMatch', label: 'Mecz', type: 'checkbox' }
                    - { property: 'match', label: 'Mecz'}
                    - { property: 'author', label: 'Autor' }
                    - { property: 'isCommentable', label: 'Zablokuj komentarze',type: 'checkbox' }
                    - { property: 'content', label: 'Wpis', type: 'ckeditor'}
                    
 
