<?php

namespace Club\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneBySlug($slug)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c','posts','match')
            ->leftJoin('c.posts','posts')
            ->leftJoin('posts.match', 'match' )
            ->where('c.slug =:slug')
            ->setParameter('slug', $slug);
        
        return $qb->getQuery()->getResult();
    }

    public function getAllCategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c','posts','match')
            ->leftJoin('c.posts','posts')
            ->leftJoin('posts.match', 'match');

        return $qb->getQuery()->getResult();
    }

    public function findAllQueryBuilder($filter = '')
    {
        $qb = $this->createQueryBuilder('category')
            ->select('category')
            ->leftJoin('category.posts', 'posts');

        if ($filter) {
            $qb->andWhere('category.name LIKE :filter')
                ->setParameter('filter', '%' . $filter . '%');
        }

        return $qb->getQuery()->getArrayResult();
    }


}
