<?php

namespace Club\BlogBundle\Repository;

use Club\BlogBundle\Entity\Post;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestComments($limit)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.post', 'p')
            ->orderBy('c.createDate', 'DESC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function createQueryBuilderForPosts(Post $post)
    {
        return $this->createQueryBuilder('comment')
            ->andWhere('comment.post = :post')
            ->setParameter('post', $post);
    }

}
